### ISSUE TITLE
Problems extracting the raw data

### ISSUE THREAD

**Issue by DradeAW** [flatironinstitute/spikeforest_recordings#6]
Hi,

I want to use `spikeforest` to test the efficacy on an algorithm I wrote, except I am having a hard time extracting the raw data from some recordings (some work, some don't).

I use the following code:
```
import numpy as np
import kachery
from spikeforest2_utils import AutoRecordingExtractor, AutoSortingExtractor
import spiketoolkit


kachery.set_config(fr="default_readonly")

recording_path = "sha1://4b90e7e52740bdd85f371e5445563e6b96ab665c/raw.mda?manifest=5e21fa57b99a1cfaefdd7a585648c13c2ce3697b" # PAIRED_KAMPFF: c14
sorting_true_path = "sha1://d7372eb6b225fce4313a0034f745ab3e81ad3143/firings_true.mda" # PAIRED_KAMPFF: c14
#recording_path = "sha1://e2bb4597b8020458a6a0ae45653041d6fb44d04f/raw.mda?manifest=9571ae17b6400ca29cedf30616f9b9578791f6fe" # PAIRED_ENGLISH: m139_200114_191955
#sorting_true_path = "sha1://6f18c2e0115a596f65c936ba62b8e2cf6693f107/firings_true.mda" # PAIRED_ENGLISH: m139_200114_191955

recording = AutoRecordingExtractor(recording_path, download=True)
sorting_true = AutoSortingExtractor(sorting_true_path)

recording.has_unscaled = True

spiketoolkit.postprocessing.export_to_phy(recording, sorting_true, "phy", max_channels_per_template=None, max_spikes_per_unit=None, ms_before=2.0, ms_after=3.0)
```

With the `PAIRED_KAMPFF` data, I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    recording = AutoRecordingExtractor(recording_path, download=True)
  File "/export/home1/users/nsr/wyngaard/dev/spikeforest/spikeforest2/spikeforest2_utils/autoextractors/autorecordingextractor.py", line 57, in __init__
    self._recording = MdaRecordingExtractor(recording_directory=path, download=download)
  File "/export/home1/users/nsr/wyngaard/dev/spikeforest/spikeforest2/spikeforest2_utils/autoextractors/mdaextractors/mdaextractors.py", line 21, in __init__
    self._dataset_params = ka.load_object(params_path)
  File "/export/home1/users/nsr/wyngaard/dev/spikeforest/kachery/kachery/core.py", line 255, in load_object
    return simplejson.load(f)
  File "/users/nsr/wyngaard/.conda/envs/spikeforest/lib/python3.8/site-packages/simplejson/__init__.py", line 467, in load
    return loads(fp.read(),
  File "/users/nsr/wyngaard/.conda/envs/spikeforest/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte
```

With the `PAIRED_ENGLISH` data, I get this error:
```
Downloading file --- (3.6 GiB): http://kachery.flatironinstitute.org/neuro1/get/sha1/e2bb4597b8020458a6a0ae45653041d6fb44d04f?channel=public&signature=51813cae90a78a35cde06641088b50cb30f6b302 -> /mnt/raid0/tmp/kachery/sha1/e2/bb/45/e2bb4597b8020458a6a0ae45653041d6fb44d04f
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    recording = AutoRecordingExtractor(recording_path, download=True)
  File "/export/home1/users/nsr/wyngaard/dev/spikeforest/spikeforest2/spikeforest2_utils/autoextractors/autorecordingextractor.py", line 57, in __init__
    self._recording = MdaRecordingExtractor(recording_directory=path, download=download)
  File "/export/home1/users/nsr/wyngaard/dev/spikeforest/spikeforest2/spikeforest2_utils/autoextractors/mdaextractors/mdaextractors.py", line 21, in __init__
    self._dataset_params = ka.load_object(params_path)
  File "/export/home1/users/nsr/wyngaard/dev/spikeforest/kachery/kachery/core.py", line 251, in load_object
    path2 = load_file(path, **kwargs)
  File "/export/home1/users/nsr/wyngaard/dev/spikeforest/kachery/kachery/core.py", line 230, in load_file
    return _hash_caches[algorithm].downloadFile(url=url0, hash=hash0, size=size0, target_path=dest)
  File "/export/home1/users/nsr/wyngaard/dev/spikeforest/kachery/kachery/localhashcache.py", line 138, in downloadFile
    raise Exception(
Exception: size of downloaded file does not match expected http://kachery.flatironinstitute.org/neuro1/get/sha1/e2bb4597b8020458a6a0ae45653041d6fb44d04f?channel=public&signature=51813cae90a78a35cde06641088b50cb30f6b302 3271999495 <> 3845958428
```

How can I fix this problem?
Thank you,

Drade

**Comment by magland** [comment]
Hi @Dradeliomecus. Please use the following updated method to obtain the recordings and ground truth sortings:

https://github.com/flatironinstitute/spikeforest

**Comment by DradeAW** [comment]
Ah alright, thanks I'll try!

I didn't know `spikeforest` was newer than `spikeforest2` ^^
